modLoader="javafml"
loaderVersion="[47,)"
license="GPLv3"
issueTrackerURL="https://github.com/Nosiphus/nosiphus-furniture-mod/issues"

[[mods]]
modId="nfm"
version="2023.08.15
displayName="Nosiphus Furniture Mod"
updateJSONURL=""
displayURL=""
logoFile="nfm.png"
credits="MrCrayFish, Ocelot"
authors="Nosiphus"
description="Nosiphus Furniture Mod is an addon to MrCrayFish's Furniture Mod that readds old furniture."

[[dependencies.nfm]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nfm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nfm]]
    modId="cfm"
    mandatory=true
    versionRange="[7.0.0-pre36,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.nfm]
    catalogueItemIcon="nfm:white_modern_chair"
    configuredBackground="minecraft:textures/block/white_concrete.png"